add git hash and build date to MainActivity
rocka/fcitx5-android-poc pull request #11
Opened 2021-11-21 13:45 UTC by oldherl

2021-11-21 13:45 UTC, oldherl commented
May be ugly implementation. Welcome any edits.

2021-11-21 17:36 UTC, rocka requested changes
Put version info under button

2021-11-21 17:36 UTC, rocka commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toTopOf="@id/open_ime_settings_guide"
```suggestion
        app:layout_constraintBottom_toBottomOf="parent"
```

2021-11-21 17:36 UTC, rocka commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toTopOf="parent"/>
```suggestion
        app:layout_constraintTop_toBottomOf="@id/open_ime_settings"/>
```

2021-11-21 17:36 UTC, rocka commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@id/version_info"
```suggestion
        app:layout_constraintTop_toTopOf="parent"
```

2021-11-22 16:27 UTC, rocka approved these changes

2021-11-22 16:52 UTC, merged